// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function T2V(arg1:string):Promise<string>;

export function V2T(arg1:Array<number>):Promise<string>;

export function VMT(arg1:string):Promise<string>;
