// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function T2V(arg1) {
  return window['go']['main']['App']['T2V'](arg1);
}

export function V2T(arg1) {
  return window['go']['main']['App']['V2T'](arg1);
}

export function VMT(arg1) {
  return window['go']['main']['App']['VMT'](arg1);
}
